### ISSUE TITLE
又发现几处笔误

### ISSUE THREAD

**Issue by xzqiaochu** [ZJU-FAST-Lab/Fast-Drone-250#10]
第十章 - VINS外参精确自标定
rostopic echo /**vins_estimator**/imu_propagate -> rostopic echo /**vins_fusion**/imu_propagate
(还有一处在 第十一章 - 自动起飞)

第十一章 - Ego-Planner实验
roslaunch **ego-planner** single_run_in_exp.launch -> roslaunch **ego_planner** single_run_in_exp.launch

**Comment by PanNeng-ZJU** [comment]
感谢，已修改
