### ISSUE TITLE
关于算法中使用的imu问题

### ISSUE THREAD

**Issue by SSZ1** [ZJU-FAST-Lab/Fast-Drone-250#15]
已经把整个项目跑起来了，但是遇到了一些问题，想咨询一下。

1.自主飞行项目中的vins使用的imu是飞控的imu，想咨询一下为什么不直接使用realsense的imu？

2.我在实机实验中，运行vins，发现vins特别容易漂，飞机自动起飞时候飞行不稳可能也与之有关。想问一下vins为什么会这么容易漂？

3.因为2中的问题，我尝试把项目中vins中接入的imu换成了realsense自带的imu，单独运行vins算法，发现没有那么容易漂了，但是在rviz中发现，它的坐标轴变动了，y轴变成垂直方向了，开了realsense-viewer才发现，realsense默认是y轴在垂直方向的，请问这是不是你们选择使用飞控imu的原因。

**Comment by PanNeng-ZJU** [comment]
1.realsense的imu没有做减震，噪声较大
2.外参标定得不对
3.如果外参标定得不对，realsense的imu由于与相机本身位移较少，所以不容易飘。 是
