### ISSUE TITLE
Web control

### ISSUE THREAD

**Issue by zyayoung** [ZJU-FAST-Lab/Fast-Drone-250#19]
I think opening multiple terminals and remote desktops for flight testing is chaotic, so I write a web frontend for visualization and setting nav points (without even using a laptop).

https://github.com/zyayoung/ego-planer-web-control

**Comment by zyayoung** [comment]
Also, mobile WIFI hotspots seem unstable, even at close distances.
How did you tackle communication with contral terminals and multiple drones?

**Comment by PanNeng-ZJU** [comment]
Very impressive, thanks a lot.
The communication for multiple drones is developed by @bigsuperZZZX
