### ISSUE TITLE
请问编译好的px4_fmu-v5_default.px4是没有定点模式吗？另外关于不同固件imu频率发布问题

### ISSUE THREAD

**Issue by goodworth1** [ZJU-FAST-Lab/Fast-Drone-250#24]
我用你们提供的固件，在添加GPS模块后，无法进入定点模式。另外我尝试了1.13版本，imu根据你们提供的命令去修改发布频率，结果发现只有50HZ左右，明显发布频率修改没有生效，在你们提供的1.11版本是可以的。如果要使用1.13固件，要怎么修改发布频率呢？你们现在有尝试使用最新pixhawk6C进行试验吗？

**Comment by PanNeng-ZJU** [comment]
1. 启动mavros后尝试一下以下命令：
rosrun mavros mavcmd long 511 105 5000 0 0 0 0 0 & sleep 1;
rosrun mavros mavcmd long 511 31 5000 0 0 0 0 0 & sleep 1;

2.没有
