### ISSUE TITLE
找不到参数dshot_config

### ISSUE THREAD

**Issue by LiangtaoZhong** [ZJU-FAST-Lab/Fast-Drone-250#25]
作者，您好，我使用v1.11.0的px4_fmu_v2的固件，找不到dshot_config参数，不能使用dshot协议电调。换成v1.13.0就能找到该参数。而您又提到v1.13有BUG，请问是致命性BUG吗？是否可以使用v1.13固件呢？谢谢

**Comment by PanNeng-ZJU** [comment]
我仅在v5的1.11固件上测试通过，其他版本的固件可能可以，你可以试试

**Comment by LiangtaoZhong** [comment]
好的 谢谢

**Comment by yjw-01** [comment]
> 作者，您好，我使用v1.11.0的px4_fmu_v2的固件，找不到dshot_config参数，不能使用dshot协议电调。换成v1.13.0就能找到该参数。而您又提到v1.13有BUG，请问是致命性BUG吗？是否可以使用v1.13固件呢？谢谢

您好，我也遇到了同样的问题，请问你使用v1.13版本的固件有遇到bug吗？
