### ISSUE TITLE
自动起飞失败

### ISSUE THREAD

**Issue by Chai8226** [ZJU-FAST-Lab/Fast-Drone-250#26]
自动起飞报错：[px4ctrl] Reject AUTO_TAKEOFF. If you have your RC connected, keep its switches at "auto hover" and "command control" states, and all sticks at the center, then takeoff again.
请教一下怎么办，通道没选择错误

**Comment by DB-PLPSlame** [comment]
你好，请问这个报错解决了吗，我也遇到了同样的错误

**Comment by striker2333** [comment]
我也遇到了相同的报错，请问您是如何解决这个问题的？十分感谢！

**Comment by zhao6868999** [comment]
Hello, I have also encountered this problem. How did you solve it？
