### ISSUE TITLE
陀螺仪零偏警告；路径规划路线异常

### ISSUE THREAD

**Issue by cbyf** [ZJU-FAST-Lab/Fast-Drone-250#30]
1. gyroscope bias initial calibration -0.00056661 0.00100545 -0.000996476
是一个警告，请问有影响吗？
2.如下图，路径规划路线异常，无人机往所规划路径的方向飘（但机头不会朝着运动的方向，看起来似乎机头不会转动，因为正常情况下，机头总朝向运动方向），请问如何解决，谢谢。
![488B0E27B8DE6A24304005E5D1F72A83](https://user-images.githubusercontent.com/97436572/201384802-0c6ff10c-d985-4eed-b938-a6e2fd911e96.jpg)

**Comment by PanNeng-ZJU** [comment]
1.没有见过这种警告，看起来问题不大
2.能提供视频吗？文字描述看不出来
