### ISSUE TITLE
飞机起飞时VINS里程计有一个较大的漂移

### ISSUE THREAD

**Issue by LChen-99** [ZJU-FAST-Lab/Fast-Drone-250#31]
飞机起飞时VINS里程计有一个较大的漂移，大概有十多厘米。
还有请问有什么办法可以获得飞机较为准确的距离地面的高度吗？

**Comment by PanNeng-ZJU** [comment]
视觉方法的z轴估计确实不太准确，如果对z轴精度要求较高，我建议你在无人机下方加装一个超声波或者激光传感器
