### ISSUE TITLE
请问px4ctrl还没有实现精确油门模型吗，好像只有在线辨识的线性模型。

### ISSUE THREAD

**Issue by LChen-99** [ZJU-FAST-Lab/Fast-Drone-250#32]
请问px4ctrl还没有实现精确油门模型吗，好像只有在线辨识的线性模型。
python的thrust_calibrate.py可以用来辨识精确模型吗？

**Comment by PanNeng-ZJU** [comment]
非线性模型标定起来比较麻烦，在不大机动飞行（比如8m/s以上）时和线性模型效果差不多，所以不建议使用。
