### ISSUE TITLE
PX4 Cntrl changes

### ISSUE THREAD

**Issue by EhrazImam** [ZJU-FAST-Lab/Fast-Drone-250#33]
Hi, I hope you are doing well as i can see here @https://github.com/ZJU-FAST-Lab/Fast-Drone-250/blob/8ff64274b161bb829653faf5946656658e7e2c9f/src/realflight_modules/px4ctrl/src/px4ctrl_node.cpp#L51 why we cant use /mavros/imu/data_raw. As what i know difference between these two is one gives you orientation and one doesn't as we have already switched off the magnetometer why we are using it. 
Thank you

**Comment by PanNeng-ZJU** [comment]
The orientation of imu is used in the 51 line of [controller.cpp](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/commit/394bfdfad137e4dc234f30e9270b99110c19c764):
u.q = imu.q * odom.q.inverse() * q;
