### ISSUE TITLE
VINS时间同步

### ISSUE THREAD

**Issue by panpanyunshi** [ZJU-FAST-Lab/Fast-Drone-250#34]
感谢实验室的工作，使用过程有些问题想再请教您们。
就是多次使用PX4+D435，VINS偶尔会启动不稳定，或起飞后也有不小飘逸。
看了VINS介绍说可以做硬件时间同步来提高性能
想请教下，用pX4和D435可以做时间同步吗，会不会对性能有提升呢，有没有一些链接资料可以供参考的呢
真的感谢哈

**Comment by PanNeng-ZJU** [comment]
@YangTiankai 请凯哥来解答一下

**Comment by dssdyx** [comment]
@panpanyunshi 可能是你的PX4传感器没有校准好，或者内部参数有问题，你用多少版本的飞控

**Comment by panpanyunshi** [comment]
感谢大佬的回答，用的是雷迅V5飞控，校准是参考px4的教程。想问下标定完后，应该看哪些参数来判断结果的好坏呢。再次感谢哈

**Comment by dongdongbh** [comment]
可以同步，参考[Multi-Camera configurations - D400](https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration) 和[px4 Camera Configuration
](https://docs.px4.io/main/en/peripherals/camera.html), 有一些麻烦，因为D435 需要1.8V触发信号
