### ISSUE TITLE
请问下整体重量是多少呀

### ISSUE THREAD

**Issue by roam-water** [ZJU-FAST-Lab/Fast-Drone-250#37]
首先非常感谢您的分享！
如题，请问安装如上机体后，整体重量如何，会不会太重了？

**Comment by PanNeng-ZJU** [comment]
见readme的Q&A：
Q: 这台飞机的载重有多少？续航有多少？能飞多远？
A: 不带额外负载起飞重量在1.1~1.2kg左右，最大起飞重量在1.8kg内，再大控制不稳且续航很短。
	不带负载续航约5分钟。
