### ISSUE TITLE
Few questions about the firmware release and Pixhawk orientation

### ISSUE THREAD

**Issue by FaboNo** [ZJU-FAST-Lab/Fast-Drone-250#39]
Dear All,

As mentioned in a previous message, instead of a pixhawk 4 mini (no more available), I had to purchase a Pixhawk 6x mini.
In your READ.ME you mentioned that we have to use the v1.11.0 but this version does not support the Pixhawk 6x (starting with v1.12.0). So the question is can you tell us why the v1.13 is not suitable, and is it still not suitable with the new hardware?

Regarding the assembling, we have to set up the pixhawk "perpendicular" to the front face of the drone. Why do we have to do this? Because of VINS? Because when we are testing the drone with the pixhawk only and the AT9S PRO, if the pilot wants to go forward, the drone will move sideway
![fast drone](https://user-images.githubusercontent.com/31440972/214070238-61af736b-6f95-4714-8bd9-72e0c816b059.png)

Thank you very much for answering the question and helping us to reproduce what you do in your lab!

**Comment by PanNeng-ZJU** [comment]
1. we were having some trouble of unstable measurement of VIO with the 1.13.0 firmware, but I think you can give it a try in the pixhawk 6c.
2. The reason why we set up the pixhawk "perpendicular" to the front face of the drone, is that it's more suitable for installation. As long as the orientation of the flight controller is configured properly in the calibration part in the QGC, you can install the flight controller any way you want.

**Comment by EhrazImam** [comment]
@FaboNo hope you are doing well were you able to run on pixhawk 6x

**Comment by FaboNo** [comment]
@EhrazImam thanks for asking :) Actually I were not able to get the 200 Hz rate for the IMU - I tried all the known recipes but cannot... So it worked not well with VINS

**Comment by EhrazImam** [comment]
Any other hardware you have used


For 200 hz create a file etc/extras.txt and add  mavlink stream -d /dev/ttyS0 -s HIGHRES_IMU -r 8000
mavlink stream -d /dev/ttyS0 -s ODOMETRY -r 8000

if it does not work try to change ttyS0 to ttyS1

**Comment by FaboNo** [comment]
@EhrazImam yes it is working by doing this (I saw it in on issue):
roslaunch mavros px4.launch &sleep 10;
rosrun mavros mavcmd long 511 105 4550 0 0 0 0 0 &sleep 1;
echo "/mavros/imu/data_raw to 200Hz"
rosrun mavros mavcmd long 511 31  4550 0 0 0 0 0 &sleep 1;
echo "/mavros/imu/data to 200Hz"
