### ISSUE TITLE
大佬您好，想请教一下关于机载处理器功率的问题 Some questions about onboard processer power

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/Fast-Drone-250#4]
您好，想请教一下，平台使用Manifold 2C运行vins Fusion和ego planner或ego swarm时，有几个问题
1. 平台供电问题，我看manifold是15.2-27v宽压输入的，但是平台使用的是4s电池，处理器是怎么供电的呢，是通过电池直接供电还是通过稳压器，如果功率太大导致电压降到15.2v以下会不会导致处理器断电，问这个问题主要是想知道大佬你们是怎么平衡性能、功率和供电的。
2.  功率问题，处理器电源管理是否需要开到performance状态呢，我看高飞老师在ego planner里建议采用performance状态去保证系统不降频，但这样运行会导致处理器功率很高，如果电池容量只有2300mah，运行demo时，大佬你们一般能飞多久啊。
3. 现在manifold 2c停产了，nx的性能也不是那么理想，大佬你们有意向替换处理器么？

**Comment by PanNeng-ZJU** [comment]
1.你说的问题确实存在,妙算2c由于一些产品本身的设计原因,在低电压(例如飞机炸鸡时,电机电流过大导致电源压降很大)时会关机,这个问题即使使用6S电池也会出现,如果想彻底解决这个问题,可以使用一个升压模块把电源电压升到20V以上来给妙算供电,实测极端情况也不会导致妙算关机.
2.机载电脑的功率相较于电机的功率是很小的,开不开高功率模式都对续航影响不大.运行demo时,续航一般在5分钟以上,是这种构型无人机的正常水平.
3.可以考虑使用比较轻薄的nuc,我们实验室也正在对nuc进行测试
