### ISSUE TITLE
Using ZED camera instead of D435

### ISSUE THREAD

**Issue by EhrazImam** [ZJU-FAST-Lab/Fast-Drone-250#40]
Hi @ZhepeiWang Hope you are doing well I want to use ZED camera instead of d435, As i am able to run it with D435 i want know what parameters i need to change apart from depth topic and intrinsic values.
Do i need to change something over here https://github.com/ZJU-FAST-Lab/Fast-Drone-250/blob/8ff64274b161bb829653faf5946656658e7e2c9f/src/planner/plan_manage/launch/advanced_param_exp.xml#L103-L110

**Comment by PanNeng-ZJU** [comment]
Basically, you just need to change the depth topic, and the intrinsic values. The _depth_filter_maxdist_ param can be changed according to the maximum sensing range of your sensor.
