### ISSUE TITLE
Drone detect id=1 instead =0 

### ISSUE THREAD

**Issue by FPSychotic** [ZJU-FAST-Lab/Fast-Drone-250#44]
In this drone detect launch make reference to ID=1 but every other launch refer ID as 0, is that right?

<launch>
  <arg name="my_id" value="1"/> 
  <arg name="odom_topic" value="/vins_fusion/imu_propagate"/>

  
  <node pkg="drone_detect" type="drone_detect" name="test_drone_detect" output="screen">
    <rosparam command="load" file="$(find drone_detect)/config/camera.yaml" />
    <rosparam command="load" file="$(find drone_detect)/config/default.yaml"/>
    <param name="my_id"      value="$(arg my_id)" />
    <param name="debug_flag" value="false" />
    <remap from="~odometry"   to="$(arg odom_topic)"/>
    <remap from="~depth" to="/camera/depth/image_rect_raw"/>
    

    

    
    

  </node>

</launch>

**Comment by PanNeng-ZJU** [comment]
The drone detect module is not used in this project.
