### ISSUE TITLE
PX4 Cntrl

### ISSUE THREAD

**Issue by EhrazImam** [ZJU-FAST-Lab/Fast-Drone-250#45]
@bigsuperZZZX @ZhepeiWang As you can see over here https://github.com/ZJU-FAST-Lab/Fast-Drone-250/issues/33#issuecomment-1331634422
I want to know if we are using VIO then why we need mavros/imu/data as far i know that mavros/imu/data gives us acc,gyro and orientation and where as /mavros/imu/data_raw we only get acc and gyro.
If you are flying over VIO, why do you need the magnetometer?
Thankyou

**Comment by bigsuperZZZX** [comment]
See https://github.com/ZJU-FAST-Lab/ego-planner/issues/68#issuecomment-1471883970
