### ISSUE TITLE
vins齐次变换矩阵填法

### ISSUE THREAD

**Issue by qllokirin** [ZJU-FAST-Lab/Fast-Drone-250#46]
感谢您地项目！
1 视频中飞控和相机有一个90度的差值，但是在我的飞机上二者都朝前，请问这种情况下旋转矩阵应该怎么写？
2 我有学习到旋转矩阵计算方法，但是我不清楚imu和相机的坐标系朝向（网上也众说纷纭），请问可以告知一下吗
3 我想确认一下 齐次变换矩阵的最后一列的xyz是以imu为原点前x左y右z来计算相机的位置吗
这真的很困扰我  期待您的解答

**Comment by PanNeng-ZJU** [comment]
1. 与飞控摆放位置无关，保持默认即可
2. 前x左y上z
3.  前x左y上z

**Comment by qllokirin** [comment]
非常感谢
