### ISSUE TITLE
有一处不理解的代码

### ISSUE THREAD

**Issue by bulingda** [ZJU-FAST-Lab/Fast-Drone-250#48]
src/realflight_modules/px4ctrl/src/input.cpp 113 行
bool RC_Data_t::check_centered()
{
    bool centered = abs(ch[0]) < 1e-5 && abs(ch[0]) < 1e-5 && abs(ch[0]) < 1e-5 && abs(ch[0]) < 1e-5;
    return centered;
}
你好，想问一下，这里所有都是ch[0]是什么意思呢？

**Comment by PanNeng-ZJU** [comment]
不好意思，这是一处bug，应为ch[0~3]
