### ISSUE TITLE
关于hover percentage的print value的问题

### ISSUE THREAD

**Issue by BizzareNathan** [ZJU-FAST-Lab/Fast-Drone-250#49]
视频中提到可以通过修改ctrl_param_fpv.yaml文件中的thrust_model：print value设置为true来打印hover percentage，但是在实际使用中开启了以后，并没有在实际的终端界面中看见这个参数的打印，只能在开始时看见一个ROS_WARN("You should disable \"print_value\" if you are in regular usage.");
请问可以提供这个的正确修改方法或者是其他可以来调整这个参数的方法吗？

**Comment by PanNeng-ZJU** [comment]
不好意思，这个功能暂时还没有，你可以去代码相应位置自行打印一下
