### ISSUE TITLE
agx xavier运行ego_planner出现问题

### ISSUE THREAD

**Issue by Jimmy-L99** [ZJU-FAST-Lab/Fast-Drone-250#50]
很感激fastlab团队做出的贡献，最近也在结合你们的视频教程弄自己的东西，我用的是jetson AGX Xavier，CUAV V5+固件版本1.11，vins-fusion替换成了vins-fusion-gpu版本，运行时GPU有20%多的使用率。问题出现在运行vins之后再运行ego_planner，终端会出现报错
[drone_0_ego_planner_node-2] process has died [pid 935, exit code -11, cmd /home/hyy/catkin_ws/devel/lib/ego_planner/ego_planner_node ~odom_world:=/vins_fusion/imu_propagate ~planning/bspline:=/drone_0_planning/bspline ~planning/data_display:=/drone_0_planning/data_display ~planning/broadcast_bspline_from_planner:=/broadcast_bspline ~planning/broadcast_bspline_to_planner:=/broadcast_bspline ~grid_map/odom:=/vins_fusion/imu_propagate ~grid_map/cloud:=nouse2 ~grid_map/pose:=nouse1 ~grid_map/depth:=/camera/depth/image_rect_raw __name:=drone_0_ego_planner_node __log:=/home/hyy/.ros/log/aacab844-ce0c-11ed-89c8-3413e862af5c/drone_0_ego_planner_node-2.log].
log file: /home/hyy/.ros/log/aacab844-ce0c-11ed-89c8-3413e862af5c/drone_0_ego_planner_node-2*.log
![ed8fcc873fccb218302de757bec9b59](https://user-images.githubusercontent.com/53935505/228482983-09f8cafd-6e99-4ead-8e82-42412c2a4d0f.png)
单独运行ego的话并不会出现报错，或者先运行ego再运行vins，过了一段时间才会出现报错。想请问一下是什么原因？有什么解决办法吗？

**Comment by PanNeng-ZJU** [comment]
目测是里程计飘了，出了地图范围限制后数组越界导致的崩溃

**Comment by otis-XJY** [comment]
> 很感激fastlab团队做出的贡献，最近也在结合你们的视频教程弄自己的东西，我用的是jetson AGX Xavier，CUAV V5+固件版本1.11，vins-fusion替换成了vins-fusion-gpu版本，运行时GPU有20%多的使用率。问题出现在运行vins之后再运行ego_planner，终端会出现报错 [drone_0_ego_planner_node-2] process has died [pid 935, exit code -11, cmd /home/hyy/catkin_ws/devel/lib/ego_planner/ego_planner_node ~odom_world:=/vins_fusion/imu_propagate ~planning/bspline:=/drone_0_planning/bspline ~planning/data_display:=/drone_0_planning/data_display ~planning/broadcast_bspline_from_planner:=/broadcast_bspline ~planning/broadcast_bspline_to_planner:=/broadcast_bspline ~grid_map/odom:=/vins_fusion/imu_propagate ~grid_map/cloud:=nouse2 ~grid_map/pose:=nouse1 ~grid_map/depth:=/camera/depth/image_rect_raw __name:=drone_0_ego_planner_node __log:=/home/hyy/.ros/log/aacab844-ce0c-11ed-89c8-3413e862af5c/drone_0_ego_planner_node-2.log]. log file: /home/hyy/.ros/log/aacab844-ce0c-11ed-89c8-3413e862af5c/drone_0_ego_planner_node-2*.log ![ed8fcc873fccb218302de757bec9b59](https://user-images.githubusercontent.com/53935505/228482983-09f8cafd-6e99-4ead-8e82-42412c2a4d0f.png) 单独运行ego的话并不会出现报错，或者先运行ego再运行vins，过了一段时间才会出现报错。想请问一下是什么原因？有什么解决办法吗？

请问您是怎么解决的呢
