### ISSUE TITLE
Question about external yaw estimator

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/Fast-Drone-250#54]
Thank you for such a great project. I have read carefully of your work. But I want to ask the question that  if the running env is indoor,which may be disturbed for Px4 FCU inner magnetometer,could the attitude controller still keep robust ?
   As I know, you don't use GPS module, meaning your drone only has one magenetometer inside the Pixhawk 4 mini. This magenetometer is not reliable because it's close to many wires, affected by current magnetic field. Here, the FCU orientation is computed by imu and magenetometer.
  Indoor env is not usually clean. It may exist some electronic devices resulting in magenetometer failure. Then the FCU orientation, specially yaw estimation may not be stable.
   So, is it necessary to make VIO yaw estimation take part in FCU Fusion? 
   Hope for your answer. Thank you so much!

**Comment by PanNeng-ZJU** [comment]
The magenetometer is not used in this project, and the yaw is estimated by the integration of imu and VIO.

**Comment by PanNeng-ZJU** [comment]
For more information, you can refer to [https://github.com/HKUST-Aerial-Robotics/VINS-Fusion](url)
