### ISSUE TITLE
你好，我希望在无人机飞行后把vins采集的地图数据保存下来，然后在其他机器上运行重定位

### ISSUE THREAD

**Issue by yjjzz12619** [ZJU-FAST-Lab/Fast-Drone-250#59]
但是在无人机上开启loop_fusion节点后，回环功能开启并不成功，也无法成功的保存地图数据。请问你们是否修改了这里vins-fusion的代码？

**Comment by PanNeng-ZJU** [comment]
没有修改，相关功能需要你自行调试

**Comment by yjjzz12619** [comment]
但是每次保存地图的时候都会报错，我不知道是哪里出了问题，您可以帮我看一下吗 谢谢！@PanNeng-ZJU
![微信图片_20230609193900](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/assets/50129416/60e393f4-d13f-4649-bf0f-0ee0f2d06f34)



> 没有修改，相关功能需要你自行调试
