### ISSUE TITLE
heading issue

### ISSUE THREAD

**Issue by skyaid** [ZJU-FAST-Lab/Fast-Drone-250#6]
Hello, thank you for a great project.

When switching the current Px4ctrl to offboard, it rotates 180 degrees.

We start by looking at the back of the aircraft, but if we change to offboard

The aircraft sees us. 

When looking at vio and ego planer rviz, the initial position is correct.

**Comment by PanNeng-ZJU** [comment]
What is the odometry you use? Did you check the odometry's coordinate system si correct?

**Comment by skyaid** [comment]
I used vins fusion gpu and odometry coodinate position is correct

I replaced the estimator file and visualization file using vins fusion provided by zju

**Comment by PanNeng-ZJU** [comment]
Sorry, I have no idea where the problem lies @skyaid

**Comment by skyaid** [comment]
@PanNeng-ZJU thanks
