### ISSUE TITLE
VINS飘一直未找到原因

### ISSUE THREAD

**Issue by EGOIST5** [ZJU-FAST-Lab/Fast-Drone-250#65]
使用的无人机是JCV-600，相机为D435i，机载电脑为jetson xavier nx，
已将VINS修改为GPU版本，即使用https://github.com/pjrambo/VINS-Fusion-gpu这里的文件替换原来的vins-fusion文件夹，并且在其中添加了相应的fast-drone-250.yaml、left.yaml、right.yaml并替换了原来的vins_rviz_config.rviz，并在fast-drone-250.yaml增加了相应的使用GPU参数，其余未做替换。并仿造ego_planner_swarm项目中将相应的CMakeList.txt内容修改set(ENABLE_CUDA true)及 set(CUDA_NVCC_FLAGS 
      -gencode arch=compute_72,code=sm_72;
    ) 
结构光也已经关闭。
但是无人机即使放在远处，VINS显示的position也将不断增加，seq达到六七千的时候x和y可能达到几十，甚至上百，一直未找到相应的原因，之后按照相应的操作去替换相应的矩阵参数，也未得到改善，并且这几次标定发现vins_output/extrinsic_parameter.txt里的内容一直不变。

**Comment by EGOIST5** [comment]
跳过标定这一步，直接进行建图模块验证，三个窗口依次输入sh shfiles/rspx4.sh、roslaunch ego_planner single_run_in_exp.launch、roslaunch ego_planner rviz.launch将会在第二个窗口报如下错误[drone_0_ego_planner_node-1] process has died [pid 41361, exit code -11, cmd /home/wzy/Fast-Drone-250-master/devel/lib/ego_planner/ego_planner_node ~odom_world:=/vins_fusion/imu_propagate ~planning/bspline:=/drone_0_planning/bspline ~planning/data_display:=/drone_0_planning/data_display ~planning/broadcast_bspline_from_planner:=/broadcast_bspline ~planning/broadcast_bspline_to_planner:=/broadcast_bspline ~grid_map/odom:=/vins_fusion/imu_propagate ~grid_map/cloud:=nouse2 ~grid_map/pose:=nouse1 ~grid_map/depth:=/camera/depth/image_rect_raw __name:=drone_0_ego_planner_node __log:=/home/wzy/.ros/log/cb4a19e6-2ab1-11ee-a637-845cf326b7db/drone_0_ego_planner_node-1.log].
log file: /home/wzy/.ros/log/cb4a19e6-2ab1-11ee-a637-845cf326b7db/drone_0_ego_planner_node-1*.log

相应的Rviz也只有坐标系，并没有得到相关的点云，有时候有那么一两下有点云，后面就报错了

**Comment by otis-XJY** [comment]
我也使用同样的机载电脑和相机，请问是如何解决的呢

**Comment by 2874160799** [comment]
请问如何解决的呢？

**Comment by EGOIST5** [comment]
我当时是矩阵参数不够准确，替换到更准确的矩阵参数后，就不会飘了

**Comment by 2874160799** [comment]
> 我当时是矩阵参数不够准确，替换到更准确的矩阵参数后，就不会飘了

是外参和内参的标定矩阵吗

**Comment by EGOIST5** [comment]
是的
