### ISSUE TITLE
运行ego-planner出现的问题

### ISSUE THREAD

**Issue by SSZ1** [ZJU-FAST-Lab/Fast-Drone-250#7]
您好！我一直都在关注你们组。首先非常感谢您能够开源自主无人机，可以预见到一定能够带动国内专业领域的发展。我在NUC上配置ego-planner这一步时，按照你们给的命令，编译完成，并且执行了`source devel/setup.bash`
在执行`roslaunch ego_planner sing_run_in_sim.launch`时报错：

**RLException: [sing_run_in_sim.launch] is neither a launch file in package [ego_planner] nor is [ego_planner] a launch file name
The traceback for the exception was written to the log file.**

请问为什么会出现这个问题，该怎么解决呢？十分感谢
![7f02b7a94e8fe28a634a3b19981a11b](https://user-images.githubusercontent.com/36888758/163386563-6b251d0b-3464-49e0-8939-73f552752d9f.jpg)

**Comment by xzqiaochu** [comment]
您好，似乎是拼写错误：single误拼成了sing
正确的写法：roslaunch ego_planner single_run_in_sim.launch
如果解决了记得close一下哈

**Comment by SSZ1** [comment]
> 

谢谢您！已经解决了，之前好像是看了没更新的readme.md，现在已经更新了，非常感谢！！！
