### ISSUE TITLE
 Reject AUTO_TAKEOFF

### ISSUE THREAD

**Issue by ranjithlesoko** [ZJU-FAST-Lab/Fast-Drone-250#79]
[ INFO] [1709288461.395479347]: PX4CTRL] Waiting for RC
[ INFO] [1709288461.402635812]: [PX4CTRL] RC received.
[ INFO] [1709288462.613087580]: [px4ctrl] Voltage=4.826, percentage=1.000
[ERROR] [1709288468.683143015]: [px4ctrl] Reject AUTO_TAKEOFF. If you have your RC connected, keep its switches at "auto hover" and "command control" states, and all sticks at the center, then takeoff again.
I'm using herelink not sort because one time its get take

**Comment by striker2333** [comment]
I also encountered the same error, How did you solve this problem? Thanks!

**Comment by ranjithlesoko** [comment]
@striker2333  what rc are  you using
