### ISSUE TITLE
发现两处笔误

### ISSUE THREAD

**Issue by xzqiaochu** [ZJU-FAST-Lab/Fast-Drone-250#8]
第八章
VScode：sudo dpkg **--i** ***.deb  ->  VScode：sudo dpkg **-i** ***.deb
rosrun plotjuggler **plotjugller**  -> rosrun plotjuggler **plotjuggler**

anyway，感谢这门课程，学到了好多东西

**Comment by PanNeng-ZJU** [comment]
感谢，已修改
