### ISSUE TITLE
自动起飞失败？

### ISSUE THREAD

**Issue by x710777335** [ZJU-FAST-Lab/Fast-Drone-250#85]
按照步骤里面操作，运行roslaunch px4ctrl run_ctrl.launch，然后再运行sh shfiles/takeoff.sh发现电机没有转动，提示reject auto_takeoff no odom ego_planner。我是用激光雷达fast-lio作为定位源的，需要改什么吗？

**Comment by zhao6868999** [comment]
Hello, I have also encountered this problem. How did you solve it？
