### ISSUE TITLE
请问Fast-Drone-250的位置控制和速度控制是否简化了？

### ISSUE THREAD

**Issue by lminjy** [ZJU-FAST-Lab/Fast-Drone-250#86]
我的基于ego-planner的探索算法给出的是PositionCommand.msg，它设定了目标点的期望位置、速度、加速度，我的仿真环境需要的控制指令是mavros_msgs/AttitudeTarget，按照px4飞控的多旋翼的控制架构来说，仿真环境里的飞控应该是有相应的角度、角速度控制器，所以为了控制仿真环境里的四旋翼，我需要实现对应的Position Controller、Velocity Controller和Acceleration and Yaw to Attitude，并在必要的地方加入前馈控制以使四旋翼在目标点处有期望的速度、加速度，可是我在Fast-Drone-250的px4ctrl只找到Acceleration and Yaw to Attitude（是在PX4CtrlFSM.cpp中controller.calculateControl计算吧？），请问是否存在对应的Position Controller和Velocity Controller？我该如何找到它们呢？
![calculateControl](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/assets/84137764/1214b431-c581-4795-bbbd-384f888e6c41)
![控制架构](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/assets/84137764/16f5d00c-005e-4c06-96f2-33a63def3093)

**Comment by lminjy** [comment]
好像是有Position Controller和Velocity Controller，但是和我理解的不太一样，按照我的理解(如方框图所示)：
位置控制器的控制输出量 $des\\_p=k_p*(des.p-odom.p)$
速度控制器期望值(控制输入量) $des\\_p+des.v-odom.v$
速度控制器的控制输出量 $des\\_v=k_v*(des\\_p+des.v-odom.v)$
因此 $des\\_acc=des.a + k_v*(des\\_p+des.v-odom.v)=des.a + k_v*(des.v-odom.v)+k_v\*k_p*(des.p-odom.p)$
所以，您是把kv*kp合成一个参数是吗？此"kp"非常规的kp是吗？
![Position Controller and Velocity Controller](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/assets/84137764/d69c16a7-dfff-4e81-b4de-ceb917434f2b)
![方框图](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/assets/84137764/8fb6b6cb-4777-45b0-b529-8c4cb3a6995f)

**Comment by lminjy** [comment]
还有个疑问，这样算前馈控制吗？des_p的单位是m，des.v和odom.v的单位是m/s，这样直接加可以吗？

**Comment by XXLiu-HNU** [comment]
【无人机系统 - 高飞组超全讲解！2021ROS暑期学校 第五天精剪回放】 https://www.bilibili.com/video/BV1Jq4y1T7QD/?p=3&share_source=copy_web&vd_source=694800f4f1ae99186a15066decbc1bc2

**Comment by XXLiu-HNU** [comment]
> 【无人机系统 - 高飞组超全讲解！2021ROS暑期学校 第五天精剪回放】 https://www.bilibili.com/video/BV1Jq4y1T7QD/?p=3&share_source=copy_web&vd_source=694800f4f1ae99186a15066decbc1bc2

这里边有无人机控制部分的内容
