### ISSUE TITLE
How to increase hz of IMU and odom 

### ISSUE THREAD

**Issue by NamDinhRobotics** [ZJU-FAST-Lab/Fast-Drone-250#97]
Thanks for your great work, 
I am struggling to increase the IMU and odometry (odom) frequency of PX4, following your guide: 

"Create a file named /etc/extras.txt in the root directory of the flight controller's SD card. Write the following lines into the file:
```
mavlink stream -d /dev/ttyACM0 -s ATTITUDE_QUATERNION -r 200
mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 200
```
This will increase the frequency of the IMU."

I inserted an SD card, created the /etc/extras.txt file, and copied the following lines into it:
```
mavlink stream -d /dev/ttyACM0 -s ATTITUDE_QUATERNION -r 200
mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 200
```

However, the MAVROS topics for IMU and odometry are still only reporting at 50 Hz. 
Could you please help me with this? ( any note dor this)

bests,

**Comment by ranjithlesoko** [comment]
@NamDinhRobotics use this 
rosrun mavros mavcmd long 511 105 5000 0 0 0 0 0 & sleep 1;
rosrun mavros mavcmd long 511 31 5000 0 0 0 0 0 & sleep 1; 

close the issue
